### ISSUE TITLE
connection error: xhr poll error

### ISSUE THREAD

**Issue by pedramardakani** [serajhqi/socketio-test-client#10]
Dear Seraj, thank you for the wonderful extension! 

However I get a connection error when creating the SocketIO server with `python-socketio 5.7.1` [[version compatibility](https://python-socketio.readthedocs.io/en/latest/intro.html#version-compatibility)]. The error sais: 
```
>>> [2022-10-17T17:35:25] disconnected 
>>> [2022-10-17T17:35:25] connection error: xhr poll error 
>>> [2022-10-17T17:35:25] connecting 
```
and stays in `connecting` mode.

I've ran the server on `http://localhost:8000` and set it in the extension. 

However, in my server logs, I can see that whenever I try connecting with `Socket.IO Test Client` a `200 OK` is printed like so:

```
INFO:     Uvicorn running on http://localhost:8000 (Press CTRL+C to quit)
INFO:     Started reloader process [94988] using StatReload
INFO:     Started server process [94990]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     127.0.0.1:35588 - "GET /socket.io/?EIO=4&transport=polling&t=OFd1pU_ HTTP/1.1" 200 OK
```

I'd gladly share more details with you if needed (I can't think of anything else right now).

**Comment by pedramardakani** [comment]
Hi again Seraj, you can clone my [demo python socketio](https://github.com/pedramardakani/python-socketio-demo) repository for a simple and quick test case. 

Please let me know if I can help any further.

**Comment by serajhqi** [comment]
185.142.80.51

**Comment by uitlaber** [comment]
yes not working too)

**Comment by serajhqi** [comment]
> Hi again Seraj, you can clone my [demo python socketio](https://github.com/pedramardakani/python-socketio-demo) repository for a simple and quick test case.
> 
> Please let me know if I can help any further.

I cloned your project, followed your instruction and ran the server. I could connect to it via the extension and didn't encounter the error message you got!

**Comment by serajhqi** [comment]
You might have not set `CORS` properly in your Socket.IO **server**. You can temporarily set the cors options:

```javascript
const io = new Server(server,{
  cors: {
    origin: "*"
  }
});
```

**Comment by bikrampun** [comment]
# Add listener

Dear Seraj, thank you for the wonderful extension!

However I can't get the reference of using the add listener functionality in this extension.

![image](https://github.com/serajhqi/socketio-test-client/assets/61911181/953cfd5c-f98b-49f0-855a-085986265e7a)

Here, the shown feature of Add Listener works but mine add listener shows like:

![image](https://github.com/serajhqi/socketio-test-client/assets/61911181/34095878-aaeb-45d2-bdf7-a6f59c897863)

how to fix this add listener problem in the my clone project?
