### ISSUE TITLE
Custom headers are not passed 

### ISSUE THREAD

**Issue by fsevenm** [serajhqi/socketio-test-client#12]
I tried to pass in this extra header below.
```json
{ "authorization": "Bearer NzY.3plHyNo5v8W245Sjjo5Tp1X6dgnpihrUPNkEtrRbmm4TpQ9RgFppN_aLIr8n" }
```
Then I inspect the incoming request on the server side, but my custom headers are not passed. Am I missing something or wrongly set it up?

**Comment by fsevenm** [comment]
Solved. I need to use a special key for additional headers. Thanks to [this thread](https://stackoverflow.com/a/35381472/9555168).
```json
{
    "extraHeaders": {
        "authorization": "Bearer NzY.3plHyNo5v8W245Sjjo5Tp1X6dgnpihrUPNkEtrRbmm4TpQ9RgFppN_aLIr8n"
    }
}
```
But for anyone who wants to pass in a token, you can use the `auth` key instead, as [stated officially here](https://socket.io/docs/v4/client-options/#auth).
```json
{
    "auth": {
        "token": "Nzg.EKZiJ55CaJdwgncaf93j6sf7KOQh6WH3Qna_AgQXmb62G2WW7GxM8U-uO_U3"
    }
}
```

**Comment by serajhqi** [comment]
Thank you for your feedback. I'll take it into account.

Cheers!
