### ISSUE TITLE
Headers Feature

### ISSUE THREAD

**Issue by hakeem750** [serajhqi/socketio-test-client#9]
How do you add headers and the likes to the request

**Comment by serajhqi** [comment]
Currently you can set credentials once you open the connection settings. Do you need to add your own custom headers?

**Comment by MrFiregore** [comment]
I need it to

**Comment by serajhqi** [comment]
OK then. I'll add this feature into the upcoming version.

**Comment by serajhqi** [comment]
Passing custom headers is now availble
